# Generated by Django 4.0.4 on 2022-06-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('frames_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('volume_cnt', models.IntegerField()),
                ('chapters_cnt', models.IntegerField()),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MangaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('chapter_start_serial', models.IntegerField()),
                ('chapter_end_serial', models.IntegerField()),
                ('manga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='source_name',
            field=models.ManyToManyField(to='manga.mangasource'),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('external_url', models.CharField(max_length=1024)),
                ('internal_url', models.CharField(max_length=1024)),
                ('img', models.BinaryField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangasource'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.volume'),
        ),
    ]
