# Generated by Django 4.0.4 on 2022-05-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='source_name',
        ),
        migrations.AddField(
            model_name='manga',
            name='source_name',
            field=models.ManyToManyField(to='manga.mangasource'),
        ),
    ]
